const evidenceA = '00000000-0000-4000-8000-000000000101';
const evidenceB = '00000000-0000-4000-8000-000000000102';
const orgId = '00000000-0000-4000-8000-000000000201';
const stakeholderId = '00000000-0000-4000-8000-000000000301';
const contactId = '00000000-0000-4000-8000-000000000401';
const backupContactId = '00000000-0000-4000-8000-000000000402';
const routeId = '00000000-0000-4000-8000-000000000501';
const interactionId = '00000000-0000-4000-8000-000000000601';

const entityFixture = (index: number, role = 'industrial target') => ({ candidateKey: `de-target-${String(index).padStart(2, '0')}`, canonicalName: `Fixture Industrial Target ${String(index).padStart(2, '0')} GmbH`, entityType: 'organization', website: `https://target-${String(index).padStart(2, '0')}.example`, countryCode: 'DE', aliases: [], externalIds: { fixture: `target-${index}` }, description: `Deterministic fictional ${role} for workflow demo`, evidenceRefs: [index % 2 === 0 ? evidenceA : evidenceB], confidence: 90 - (index % 10) });
const ecosystemEntities = Array.from({ length: 20 }, (_, index) => entityFixture(index + 1, index < 10 ? 'reachable buyer' : 'ecosystem organization'));
const competitorFixtures = Array.from({ length: 3 }, (_, index) => ({ entityCandidate: entityFixture(101 + index, 'competitor'), marketPresenceSummary: 'Deterministic European industrial market presence.', routePatterns: ['channel', 'direct_purchase'], localChannels: [], exhibitions: [], publicCustomers: [], certifications: ['ISO 9001'], serviceNetwork: ['Germany'], marketMinimums: ['Documented compliance'], opportunityGaps: ['Public onboarding path'], evidenceRefs: [evidenceA, evidenceB], confidence: 80 - index }));
const opinionFixtures = Array.from({ length: 5 }, (_, index) => ({ organization: entityFixture(201 + index, 'industry organization'), topic: `German industrial sourcing signal ${index + 1}`, positionSummary: 'Buyers prioritize traceability and responsive technical documentation.', marketImplication: 'Lead with evidence-backed qualification materials.', credibilityScore: 75 + index, contactable: index % 2 === 0, evidenceRefs: [index % 2 === 0 ? evidenceA : evidenceB] }));

const envelope = (result: unknown) => ({ result, proposedClaims: [], unknowns: [], contradictions: [], recommendedEvents: [], quality: { schemaValid: true, evidenceCoverage: 100, confidence: 85 } });

export const deterministicAgentFixtures = new Map<string, unknown>([
  ['mission_compiler', envelope({ company: { name: 'NovaFlow Industrial Co', website: 'https://novaflow.example', productSummary: 'Industrial ball, gate and control valves' }, markets: [{ countryCode: 'DE', countryName: 'Germany', targetIndustries: ['Chemical Processing', 'Water Treatment'], outputLanguages: ['en', 'de'] }], targetProfiles: [{ type: 'distributor', description: 'German industrial valve distributor' }, { type: 'epc', description: 'Chemical and water EPC' }], objectives: ['Build verified market-entry opportunities'], successCriteria: ['Approve three routes', 'Find twenty targets', 'Generate five action cards'], knownFacts: ['Products are industrial valves'], initialAssumptions: [{ statement: 'Distributor route may shorten entry time', confidence: 60 }], openQuestions: ['Which certifications are currently valid?'], budget: { maxTargets: 20, maxContactPaths: 160, maxSearchCalls: 80, maxBrowserPages: 120, maxAgentRuns: 200, maxModelTokens: 1000000, weeklyRefreshTargets: 20 } })],
  ['capability_evidence_extractor', envelope({ claims: [{ category: 'product', statement: 'Company publicly lists industrial ball valves', status: 'observed', confidence: 90, evidenceRefs: [evidenceA], currentMissionImpact: 'high' }], missingCapabilities: [{ capability: 'PED certification', routeDependency: 'German EPC route', questionForUser: 'Please provide current PED certification evidence.' }] })],
  ['market_route_researcher', envelope({ routes: [
    { routeType: 'channel', title: 'German distributor route', hypothesis: 'Qualified local distributors can provide market access and service coverage.', applicableScenarios: ['Standard industrial valve portfolio'], keyEntityTypes: ['organization'], keyStakeholderRoles: ['distributor'], primaryChannels: ['role_email', 'contact_form'], capabilityRequirements: ['Distributor-ready commercial terms'], supportingEvidenceRefs: [evidenceA, evidenceB], counterEvidenceRefs: [], confidence: 82, entryDifficulty: 45, timeToFirstContactDays: 21, resourceIntensity: 40, rank: 1 },
    { routeType: 'epc', title: 'Chemical EPC route', hypothesis: 'EPC vendor onboarding can create project-specific demand.', applicableScenarios: ['Chemical projects'], keyEntityTypes: ['organization', 'project'], keyStakeholderRoles: ['epc_engineer', 'procurement'], primaryChannels: ['supplier_registration', 'role_email'], capabilityRequirements: ['Project documentation'], supportingEvidenceRefs: [evidenceA, evidenceB], counterEvidenceRefs: [], confidence: 78, entryDifficulty: 70, timeToFirstContactDays: 45, resourceIntensity: 65, rank: 2 },
    { routeType: 'direct_purchase', title: 'Industrial end-user supplier route', hypothesis: 'Supplier registration provides a direct purchasing path.', applicableScenarios: ['Maintenance and replacement'], keyEntityTypes: ['organization'], keyStakeholderRoles: ['supplier_onboarding', 'procurement'], primaryChannels: ['supplier_registration'], capabilityRequirements: ['European compliance evidence'], supportingEvidenceRefs: [evidenceA, evidenceB], counterEvidenceRefs: [], confidence: 74, entryDifficulty: 75, timeToFirstContactDays: 60, resourceIntensity: 70, rank: 3 },
  ] })],
  ['competitor_researcher', envelope({ competitors: competitorFixtures })],
  ['expert_signal_researcher', envelope({ opinions: opinionFixtures })],
  ['ecosystem_mapper', envelope({ entities: ecosystemEntities, relationships: ecosystemEntities.slice(1).map((entity, index) => ({ sourceCandidateKey: ecosystemEntities[0]!.candidateKey, targetCandidateKey: entity.candidateKey, relationshipType: index % 2 === 0 ? 'supplies_to' : 'partners_with', confidence: 70 + (index % 10), evidenceRefs: [index % 2 === 0 ? evidenceA : evidenceB] })) })],
  ['target_ranker', envelope({ targets: ecosystemEntities.slice(0, 10).map((entity, index) => ({ organizationName: entity.canonicalName, website: entity.website, marketRole: index % 2 === 0 ? 'distributor' : 'end_user', primaryRouteTitle: 'German distributor route', productFit: 85 - index, routeFit: 88 - index, demandSignal: 72 - index, contactability: 78 - index, evidenceQuality: 80 - index, finalScore: 82 - index, rationale: 'Deterministic evidence-backed BM1 target ranking.', evidenceRefs: entity.evidenceRefs })) })],
  ['entity_resolver', envelope({ decision: 'create', canonicalName: 'RheinWerk Distribution GmbH', confidence: 90, reasons: ['No matching official domain'], evidenceRefs: [evidenceA] })],
  ['stakeholder_mapper', envelope({ stakeholders: [{ roleType: 'procurement', title: 'Procurement Department', decisionInfluence: 80, contactPriority: 1, relevanceReason: 'Owns supplier screening', evidenceRefs: [evidenceA], confidence: 85 }] })],
  ['contact_path_finder', envelope({ contactPoints: [{ stakeholderRoleType: 'procurement', contactType: 'role_email', value: 'sales@rheinwerk.example', normalizedValue: 'sales@rheinwerk.example', label: 'Sales', isPublic: true, contactEvidenceRefs: [evidenceA], employmentEvidenceRefs: [], sourceAuthority: 'official_organization', independentGroupKeys: ['rheinwerk.example'], confidence: 90, language: 'de', timezone: 'Europe/Berlin', recommendedRank: 1 }, { stakeholderRoleType: 'procurement', contactType: 'contact_form', value: 'https://rheinwerk.example/contact', normalizedValue: 'https://rheinwerk.example/contact', label: 'Contact form', isPublic: true, contactEvidenceRefs: [evidenceB], employmentEvidenceRefs: [], sourceAuthority: 'official_organization', independentGroupKeys: ['rheinwerk.example'], confidence: 80, language: 'de', timezone: 'Europe/Berlin', recommendedRank: 2 }] })],
  ['opportunity_qualifier', envelope({ hypothesis: 'Distributor fit and public contact path justify an initial qualification call.', recommendedStatus: 'contact_path_verified', commercialValueBand: 'high', estimatedSalesHours: 8, estimatedTechnicalHours: 4, estimatedMarketCostPoints: 5, scores: { productFit: 85, routeFit: 88, demandSignal: 65, timingSignal: 60, stakeholderRelevance: 80, contactability: 90, evidenceQuality: 80, strategicValue: 75 }, rationale: { productFit: 'Portfolio overlap', contactability: 'Official role path' }, nextAction: 'Send a qualification email', evidenceRefs: [evidenceA, evidenceB], unknowns: ['Annual demand volume'] })],
  ['action_card_builder', envelope({ cardType: 'outreach', targetRoleLabel: 'Procurement Department', channel: 'role_email', objective: 'Confirm product fit and distributor onboarding process', contactReason: 'Product portfolio aligns with industrial valve distribution', timingReason: 'Current market-route research identified an active public channel', stakeholderInterest: 'Reliable supply, documentation and local support readiness', valueHypothesis: 'A documented valve portfolio may expand qualified sourcing options', emailSubject: 'Industrial valve portfolio for German distribution review', emailBody: 'Hello, we would like to confirm whether our documented industrial valve portfolio fits your supplier review process.', socialMessage: 'Could we identify the right person for industrial valve supplier review?', callOpening: 'I am calling to confirm the correct supplier qualification route.', contactFormMessage: 'Please direct this supplier qualification inquiry to the relevant team.', attachmentsRequired: ['Product catalogue', 'Current certificates'], followUpPlan: [{ offsetDays: 3, channel: 'role_email', objective: 'Confirm receipt' }, { offsetDays: 7, channel: 'contact_form', objective: 'Use backup path' }], successSignals: ['Reply from relevant department', 'Supplier requirements shared'], completionSignals: ['Qualification call scheduled'], researchPlan: ['Verify the official procurement contact path on the target website'], unknowns: ['The correct public procurement contact path is not yet verified'], criticalUnknowns: [], evidenceRefs: [evidenceA, evidenceB] })],
  ['interaction_interpreter', envelope({ interactionId, interactionEvidenceRef: evidenceA, extractedFacts: [{ claimType: 'qualification', statement: 'Target requested current certification documents', valueJson: { requirement: 'current certification documents' }, status: 'observed', confidence: 95, evidenceRefs: [evidenceA] }], contactUpdates: [{ contactPointId: contactId, proposedStatus: 'manually_confirmed', evidenceRefs: [evidenceA], reason: 'Contact replied' }], routeUpdates: [{ routeId, confidenceDelta: 5, evidenceRefs: [evidenceA], reason: 'Real response confirms route viability' }], opportunityTransition: { expectedFrom: 'contacted', to: 'responded', trigger: 'response_recorded', evidenceRefs: [evidenceA], reason: 'The target replied' }, scoreUpdate: { dimensions: { productFit: 85, routeFit: 90, demandSignal: 80, timingSignal: 75, stakeholderRelevance: 85, contactability: 100, evidenceQuality: 90, strategicValue: 75 }, rationale: { demandSignal: 'Direct response' }, evidenceRefs: [evidenceA] }, nextAction: { regenerateActionCard: true, objective: 'Send requested certificates' }, unresolvedQuestions: [] })],
]);
