import { CheckCircle2, Download, ShieldCheck } from 'lucide-react';
import { CommandButton } from '@/components/command-button';
import { EmptyState, ErrorState } from '@/components/states';
import { Panel } from '@/components/panel';
import { PageHeader } from '@/components/page-header';
import { Confidence, StatusBadge } from '@/components/status';
import { safeApi } from '@/lib/api';
import { formatDate } from '@/lib/format';
import type { ContactPoint, ContactPointDetail } from '@/lib/types';

export default async function ContactPathsPage({ params }: { params: Promise<{ missionId: string }> }) {
  const { missionId } = await params;
  const contactResult = await safeApi<ContactPoint[]>(`/api/v1/missions/${missionId}/contact-points`);
  if (contactResult.error) return <ErrorState message={contactResult.error.message} />;
  const contacts = contactResult.data ?? [];
  const detailResults = await Promise.all(contacts.map((contact) => safeApi<ContactPointDetail>(`/api/v1/missions/${missionId}/contact-points/${contact.id}`)));
  const details = detailResults.flatMap((result) => result.data ? [result.data] : []);
  return <><PageHeader title="公开联系方式与触达路径" description="每条路径都展示来源快照、精确摘录、定位、验证事实和验证历史。" actions={<button className="button button-secondary"><Download />导出</button>} />{details.length === 0 ? <Panel><EmptyState title="尚未发现触达路径" description="利益相关者映射完成后，系统会优先从官方来源寻找主要路径和备用路径。" /></Panel> : <div className="stack">{details.map((detail) => <Panel key={detail.contactPoint.id} title={`${detail.organization?.canonicalName ?? '未知组织'} · ${detail.contactPoint.value}`} description={`${detail.contactPoint.contactType} · ${detail.stakeholderRole?.title ?? detail.stakeholderRole?.roleType ?? '组织路径'}`} action={<StatusBadge value={detail.verification.currentStatus} />}><div className="split-layout" style={{ marginTop: 0 }}><div className="stack"><div><div className="cell-secondary">验证置信度</div><Confidence value={detail.verification.confidence} /></div><div><div className="cell-secondary">验证事实</div><pre style={{ whiteSpace: 'pre-wrap', fontSize: 12 }}>{JSON.stringify(detail.verification.facts, null, 2)}</pre></div><details><summary className="cell-link">验证历史（{detail.verification.history.length}）</summary>{detail.verification.history.map((record) => <div key={record.id} style={{ padding: '8px 0' }}><strong>{record.method} · {record.result} · {record.score}</strong><div className="cell-secondary">{formatDate(record.verifiedAt)}</div></div>)}</details></div><div className="stack"><strong>证据来源（{detail.sources.length}）</strong>{detail.sources.map((source) => <article key={`${source.evidenceId}:${source.relationType}`} style={{ padding: 12, border: '1px solid var(--border)', borderRadius: 8 }}><div><StatusBadge value={source.authority} /> <span className="badge badge-neutral">{source.relationType}</span></div><p style={{ margin: '8px 0' }}>{source.excerpt}</p>{source.url && <a className="cell-link" href={source.url} target="_blank" rel="noreferrer">{source.publisher ?? source.url}</a>}<div className="cell-secondary">定位：{JSON.stringify(source.locator)} · 快照 {source.contentHash.slice(0, 12)}… · {formatDate(source.fetchedAt)}</div></article>)}<div className="row-actions"><CommandButton path={`/api/v1/missions/${missionId}/contact-points/${detail.contactPoint.id}/verify`} label="重新验证" /><CommandButton path={`/api/v1/missions/${missionId}/contact-points/${detail.contactPoint.id}/confirm`} label="手动确认" className="button button-ghost" /><CommandButton path={`/api/v1/missions/${missionId}/contact-points/${detail.contactPoint.id}/mark-stale`} label="标记失效" className="button button-ghost" /></div></div></div></Panel>)}</div>}<div style={{ height: 18 }} /><div className="split-layout"><Panel title="验证事实"><div className="stack"><Score icon={<ShieldCheck />} label="官方组织精确列出联系方式" /><Score icon={<CheckCircle2 />} label="多个独立来源组交叉确认" /><Score icon={<CheckCircle2 />} label="格式检查通过" /><Score icon={<CheckCircle2 />} label="人员任职证据独立确认" /></div></Panel><Panel title="Contact Gate"><p style={{ margin: 0 }}>状态完全由结构化 ContactVerificationFacts 推导；界面不再依赖人工加分规则。</p></Panel></div></>;
}

function Score({ icon, label }: { icon: React.ReactNode; label: string }) { return <div style={{ display: 'flex', alignItems: 'center', gap: 9 }}><span style={{ color: 'var(--primary)', display: 'grid' }}>{icon}</span><span>{label}</span></div>; }
