export interface Mission { id: string; name: string; companyName: string; companyWebsite: string; productScope: string; targetCountries: string[]; targetIndustries: string[]; objective: string; successDefinition: string; outputLanguages: string[]; budgetConfig: Record<string, number>; status: string; currentStage: string; workflowId?: string | null; createdAt: string; updatedAt: string }
export interface MissionMetrics { approvedRoutes: number; targets: number; verifiedContacts: number; actionCards: number; opportunities: number }
export interface Progress { stage: string; stageProgress?: number; completedSteps: string[]; runningSteps?: string[]; pendingSteps?: string[]; failedSteps?: string[]; budgetUsage?: Record<string, number>; pendingUserActions?: string[]; childOpportunities?: Record<string, { workflowId: string; status: string; milestone: string; actionCardId?: string }>; childOpportunityTotal?: number; childOpportunityActionReady?: number; childOpportunityActive?: number; childOpportunityClosed?: number; readModelVersion: number; lastEventId: string | null }
export interface Claim { id: string; claimType: string; statement: string; status: string; confidence: number; impactLevel: string; createdAt: string; updatedAt: string; valueJson: unknown }
export interface SourceRecord { id: string; sourceType: string; url?: string; title?: string; publisher?: string; language?: string; countryCode?: string; status: string; lastFetchedAt: string; latestSnapshotId?: string }
export interface MarketRoute { id: string; routeType: string; title: string; hypothesis: string; keyEntityTypes: string[]; keyStakeholderRoles: string[]; primaryChannels: string[]; confidence: number; entryDifficulty: number; resourceIntensity: number; timeToFirstContactDays: number; rank: number; status: string; evidenceSummary: string; counterEvidenceSummary: string; artifactVersionId: string }
export interface EntityRow { entity: { id: string; canonicalName: string; entityType: string; website?: string; countryCode?: string; city?: string; description?: string; status: string }; mission: { marketRoles: string[]; relevanceScore: number; discoveryReason: string; targetStatus: string; primaryRouteId?: string } | null }
export interface Relationship { id: string; sourceEntityId: string; targetEntityId: string; relationshipType: string; confidence: number; status: string }
export interface ContactPoint { id: string; organizationId: string; personId?: string; stakeholderRoleId?: string; contactType: string; value: string; label?: string; verificationStatus: string; confidence: number; firstSeenAt: string; lastVerifiedAt?: string; preferredRank?: number; language?: string; timezone?: string; sourceId: string }
export interface ContactPointDetail { contactPoint: ContactPoint; organization?: { canonicalName: string }; person?: { canonicalName: string }; stakeholderRole?: { roleType: string; title?: string }; verification: { currentStatus: string; confidence: number; lastVerifiedAt?: string; facts: Record<string, unknown>; history: Array<{ id: string; method: string; result: string; score: number; facts: Record<string, unknown>; verifiedAt: string }> }; sources: Array<{ evidenceId: string; relationType: string; authority: string; url?: string; publisher?: string; excerpt: string; locator: Record<string, unknown>; fetchedAt: string; contentHash: string }> }
export interface Opportunity { id: string; missionId: string; organizationId: string; routeId: string; title: string; hypothesis: string; status: string; priority: string; score: number; evidenceConfidence: string; commercialValueBand: string; estimatedSalesHours: string; estimatedTechnicalHours: string; resourceEfficiency: string; nextAction: string; ownerId?: string; createdAt: string; updatedAt: string }
export interface ActionCard { id: string; opportunityId: string; versionNo: number; status: string; channel: string; objective: string; contactReason: string; timingReason: string; stakeholderInterest: string; valueHypothesis: string; emailSubject?: string; emailBody?: string; socialMessage?: string; callOpening?: string; followUpPlan: unknown[]; ownerId?: string; dueAt?: string; updatedAt: string }
export interface ActionCardRow { actionCard: ActionCard; opportunity: Opportunity }
export interface TimelineItem { eventId: string; eventType: string; actorType: string; actorDisplayName?: string; aggregateType: string; aggregateId: string; correlationId: string; causationId?: string; aggregateVersion: number; schemaVersion: number; title: string; summary: string; evidenceRefs: string[]; occurredAt: string }
export interface RunItem { runId: string; runType: string; skillKey: string; status: string; modelName: string; contextVersion: number; inputContextHash: string; promptVersion?: number; evidenceItemIds: string[]; toolRuns: Array<Record<string, unknown>>; inputTokens: number; outputTokens: number; costAmount: string; durationMs?: number; startedAt: string; completedAt?: string; errorMessage?: string }
export interface CommandReceipt { commandId: string; correlationId: string; aggregateId: string; workflowId: string; acceptedAt: string; missionId?: string; interactionId?: string }
export interface RefreshProposal { artifact: { id: string; title: string; artifactType: string }; version: { id: string; versionNo: number; status: string; payload: Record<string, unknown>; summary: string; createdAt: string } }
