import { integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from 'drizzle-orm/pg-core';
import { tenants } from './auth.js';
import { missions } from './missions.js';

export const missionDashboardReadModel = pgTable('mission_dashboard_read_model', {
  missionId: uuid('mission_id').primaryKey().references(() => missions.id, { onDelete: 'cascade' }),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }),
  missionName: varchar('mission_name', { length: 200 }).notNull(),
  companyName: varchar('company_name', { length: 200 }).notNull(),
  targetCountries: text('target_countries').array().notNull(),
  status: varchar('status', { length: 40 }).notNull(),
  currentStage: varchar('current_stage', { length: 80 }).notNull(),
  approvedRouteCount: integer('approved_route_count').notNull().default(0),
  targetCount: integer('target_count').notNull().default(0),
  verifiedContactCount: integer('verified_contact_count').notNull().default(0),
  actionCardCount: integer('action_card_count').notNull().default(0),
  pendingApprovalCount: integer('pending_approval_count').notNull().default(0),
  highPriorityOpportunityCount: integer('high_priority_opportunity_count').notNull().default(0),
  weeklyInteractionCount: integer('weekly_interaction_count').notNull().default(0),
  totalCostAmount: numeric('total_cost_amount'),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const missionProgressReadModel = pgTable('mission_progress_read_model', {
  missionId: uuid('mission_id').primaryKey().references(() => missions.id, { onDelete: 'cascade' }),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }),
  stage: varchar('stage', { length: 80 }).notNull(),
  stageProgress: integer('stage_progress').notNull(),
  completedSteps: jsonb('completed_steps').notNull().$type<string[]>(),
  runningSteps: jsonb('running_steps').notNull().$type<string[]>(),
  pendingSteps: jsonb('pending_steps').notNull().$type<string[]>(),
  failedSteps: jsonb('failed_steps').notNull().$type<string[]>(),
  activeChildWorkflows: integer('active_child_workflows').notNull().default(0),
  workflowRunId: varchar('workflow_run_id', { length: 240 }),
  readModelVersion: integer('read_model_version').notNull().default(0),
  childOpportunityTotal: integer('child_opportunity_total').notNull().default(0),
  childOpportunityActionReady: integer('child_opportunity_action_ready').notNull().default(0),
  childOpportunityActive: integer('child_opportunity_active').notNull().default(0),
  childOpportunityClosed: integer('child_opportunity_closed').notNull().default(0),
  lastEventId: uuid('last_event_id'),
  budgetUsage: jsonb('budget_usage').notNull().$type<Record<string, number>>(),
  pendingUserActions: jsonb('pending_user_actions').notNull().$type<string[]>(),
  executionMode: varchar('execution_mode', { length: 20 }).notNull().default('live'),
  currentDecision: varchar('current_decision', { length: 80 }),
  nextAction: text('next_action'),
  candidateTargetCount: integer('candidate_target_count').notNull().default(0),
  selectedTargetCount: integer('selected_target_count').notNull().default(0),
  approvedActionCardCount: integer('approved_action_card_count').notNull().default(0),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const targetListReadModel = pgTable('target_list_read_model', {
  missionId: uuid('mission_id').notNull().references(() => missions.id, { onDelete: 'cascade' }),
  entityId: uuid('entity_id').notNull(),
  organizationName: varchar('organization_name', { length: 300 }).notNull(),
  website: text('website'),
  countryCode: varchar('country_code', { length: 2 }),
  marketRoles: text('market_roles').array().notNull(),
  primaryRouteTitle: varchar('primary_route_title', { length: 240 }),
  productFit: integer('product_fit').notNull(),
  demandSignal: integer('demand_signal').notNull(),
  contactability: integer('contactability').notNull(),
  evidenceQuality: integer('evidence_quality').notNull(),
  finalScore: integer('final_score').notNull(),
  targetStatus: varchar('target_status', { length: 40 }).notNull(),
  opportunityId: uuid('opportunity_id'),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex('target_read_model_uidx').on(table.missionId, table.entityId)]);

export const contactPathReadModel = pgTable('contact_path_read_model', {
  missionId: uuid('mission_id').notNull().references(() => missions.id, { onDelete: 'cascade' }),
  contactPointId: uuid('contact_point_id').notNull(),
  organizationId: uuid('organization_id').notNull(),
  organizationName: varchar('organization_name', { length: 300 }).notNull(),
  stakeholderRoleId: uuid('stakeholder_role_id'),
  stakeholderRoleType: varchar('stakeholder_role_type', { length: 80 }),
  personName: varchar('person_name', { length: 300 }),
  personTitle: varchar('person_title', { length: 240 }),
  contactType: varchar('contact_type', { length: 80 }).notNull(),
  value: text('value').notNull(),
  sourceTitle: text('source_title'),
  sourceUrl: text('source_url'),
  verificationStatus: varchar('verification_status', { length: 80 }).notNull(),
  verificationScore: integer('verification_score').notNull(),
  lastVerifiedAt: timestamp('last_verified_at', { withTimezone: true }),
  preferredRank: integer('preferred_rank'),
  usageStatus: varchar('usage_status', { length: 40 }),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex('contact_read_model_uidx').on(table.missionId, table.contactPointId)]);

export const opportunityBoardReadModel = pgTable('opportunity_board_read_model', {
  missionId: uuid('mission_id').notNull().references(() => missions.id, { onDelete: 'cascade' }),
  opportunityId: uuid('opportunity_id').notNull(),
  organizationName: varchar('organization_name', { length: 300 }).notNull(),
  routeTitle: varchar('route_title', { length: 240 }).notNull(),
  status: varchar('status', { length: 60 }).notNull(),
  priority: varchar('priority', { length: 20 }).notNull(),
  score: integer('score').notNull(),
  commercialValueBand: varchar('commercial_value_band', { length: 40 }).notNull(),
  resourceEfficiency: numeric('resource_efficiency').notNull(),
  primaryContactSummary: text('primary_contact_summary'),
  nextAction: text('next_action').notNull(),
  ownerName: varchar('owner_name', { length: 120 }),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex('opportunity_board_read_model_uidx').on(table.missionId, table.opportunityId)]);

export const actionQueueReadModel = pgTable('action_queue_read_model', {
  missionId: uuid('mission_id').notNull().references(() => missions.id, { onDelete: 'cascade' }),
  actionCardId: uuid('action_card_id').notNull(),
  opportunityId: uuid('opportunity_id').notNull(),
  organizationName: varchar('organization_name', { length: 300 }).notNull(),
  stakeholderSummary: text('stakeholder_summary').notNull(),
  primaryContactSummary: text('primary_contact_summary'),
  status: varchar('status', { length: 40 }).notNull(),
  channel: varchar('channel', { length: 80 }),
  objective: text('objective').notNull(),
  ownerName: varchar('owner_name', { length: 120 }),
  dueAt: timestamp('due_at', { withTimezone: true }),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex('action_queue_read_model_uidx').on(table.missionId, table.actionCardId)]);

export const timelineReadModel = pgTable('timeline_read_model', {
  eventId: uuid('event_id').primaryKey(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }),
  missionId: uuid('mission_id').notNull().references(() => missions.id, { onDelete: 'cascade' }),
  eventType: varchar('event_type', { length: 160 }).notNull(),
  actorType: varchar('actor_type', { length: 40 }).notNull(),
  actorDisplayName: varchar('actor_display_name', { length: 120 }),
  aggregateType: varchar('aggregate_type', { length: 80 }).notNull(),
  aggregateId: uuid('aggregate_id').notNull(),
  correlationId: uuid('correlation_id').notNull(),
  causationId: uuid('causation_id'),
  aggregateVersion: integer('aggregate_version').notNull(),
  schemaVersion: integer('schema_version').notNull(),
  title: varchar('title', { length: 240 }).notNull(),
  summary: text('summary').notNull(),
  evidenceRefs: uuid('evidence_refs').array().notNull(),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull(),
});

export const runReadModel = pgTable('run_read_model', {
  runId: uuid('run_id').primaryKey(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }),
  missionId: uuid('mission_id').notNull().references(() => missions.id, { onDelete: 'cascade' }),
  runType: varchar('run_type', { length: 80 }).notNull(),
  skillKey: varchar('skill_key', { length: 120 }).notNull(),
  status: varchar('status', { length: 40 }).notNull(),
  modelName: varchar('model_name', { length: 120 }).notNull(),
  contextVersion: integer('context_version').notNull().default(1),
  inputContextHash: varchar('input_context_hash', { length: 128 }).notNull(),
  promptVersion: integer('prompt_version'),
  evidenceItemIds: uuid('evidence_item_ids').array().notNull().default([]),
  toolRuns: jsonb('tool_runs').notNull().$type<Array<Record<string, unknown>>>().default([]),
  inputTokens: integer('input_tokens'),
  outputTokens: integer('output_tokens'),
  costAmount: numeric('cost_amount'),
  durationMs: integer('duration_ms'),
  traceId: varchar('trace_id', { length: 160 }),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  errorMessage: text('error_message'),
});

export const projectionCheckpoints = pgTable('projection_checkpoints', {
  consumerName: varchar('consumer_name', { length: 120 }).primaryKey(),
  lastEventId: uuid('last_event_id'),
  lastOccurredAt: timestamp('last_occurred_at', { withTimezone: true }),
  processedCount: integer('processed_count').notNull().default(0),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const projectionFailures = pgTable('projection_failures', {
  id: uuid('id').primaryKey().defaultRandom(),
  consumerName: varchar('consumer_name', { length: 120 }).notNull(),
  eventId: uuid('event_id').notNull(),
  tenantId: uuid('tenant_id').notNull().references(() => tenants.id, { onDelete: 'cascade' }),
  attempts: integer('attempts').notNull().default(1),
  errorCode: varchar('error_code', { length: 120 }).notNull(),
  errorMessage: text('error_message').notNull(),
  nextRetryAt: timestamp('next_retry_at', { withTimezone: true }).notNull(),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => [uniqueIndex('projection_failures_consumer_event_uidx').on(table.consumerName, table.eventId)]);
