import { describe,it,expect,vi } from 'vitest';
const state=vi.hoisted(()=>({runId:'run-one',firstExecutionRunId:'first-one',workflowId:'mission:t:m'}));
vi.mock('@temporalio/workflow',()=>({workflowInfo:()=>state}));
import { activityScope } from '../../packages/workflows/src/activity-scope.js';
import { TemporalGateway } from '../../packages/workflows/src/client.js';
import { activityBusinessRequestHash,activityIdentity,ActivityService } from '../../apps/worker/src/activities.js';
import { executionControl } from '@imea/agents';
const input={tenantId:'t',missionId:'m'};
describe('Mission execution identity contract',()=>{
 it('preserves the historical v1 argument shape',()=>{expect(activityScope(input,'compileMission','m')).toEqual({...input,ownershipRunId:'first-one',idempotencyKey:'mission:t:m:compileMission:m',correlationId:state.runId,requestedBy:{type:'system',id:'mission:t:m'}})});
 it('keeps recover key stable while fencing owner changes; restart uses a different key',()=>{const v2={...input,scopeVersion:2 as const,missionExecutionId:'execution-one'};const a=activityScope(v2,'compileMission','m');state.runId='reset-run';const b=activityScope(v2,'compileMission','m');expect(a.idempotencyKey).toBe(b.idempotencyKey);expect(a.ownershipRunId).not.toBe(b.ownershipRunId);expect(activityScope({...v2,missionExecutionId:'execution-two'},'compileMission','m').idempotencyKey).not.toBe(a.idempotencyKey);expect(activityIdentity(b,'compileMission')).toEqual({endpoint:'activity:v2:compileMission',key:'v2:execution-one:m'});});
 it('hashes normalized business fields only, preserving meaningful array order',()=>{const a={...activityScope({...input,scopeVersion:2,missionExecutionId:'e'},'x','m'),budget:{a:1,b:2},targets:['a','b']};const b={...a,ownershipRunId:'new',correlationId:'other',missionExecutionId:'new-execution',budget:{b:2,a:1}};expect(activityBusinessRequestHash(a)).toBe(activityBusinessRequestHash(b));expect(activityBusinessRequestHash({...b,targets:['b','a']})).not.toBe(activityBusinessRequestHash(a));});
 it('loadMission only reads, never consults persistent idempotency',async()=>{const s=Object.create(ActivityService.prototype);s.mission=vi.fn(async()=>({id:'m',budgetConfig:{maxTargets:10},productScope:'valves',targetCountries:['RU'],targetProfiles:[{type:'distributor'}]}));s.idempotent=vi.fn(()=>{throw Error('must not call')});expect(await s.loadMission(input)).toMatchObject({id:'m',topTargetLimit:10,supplierKnown:false});expect(s.idempotent).not.toHaveBeenCalled();});
 it('rejects stale owner distinctly and accepts the current Reset owner',async()=>{const s=Object.create(ActivityService.prototype);const tx={execute:vi.fn(),select:()=>({from:()=>({where:async()=>[{runId:'reset-run',workflowId:'mission:t:m'}]})})};await expect(s.assertExecutionOwner({...input,ownershipRunId:'old'},tx)).rejects.toMatchObject({type:'ACTIVITY_STALE_OWNER',nonRetryable:true});await executionControl.run({workflowId:'mission:t:m',workflowRunId:'reset-run'},()=>s.assertExecutionOwner({...input,ownershipRunId:'old-history-owner'},tx));});
 it('restart supplies a fresh v2 identity on every explicit invocation',async()=>{const start=vi.fn();const gateway=Reflect.construct(TemporalGateway,[{}, {workflow:{start}},'queue']);await gateway.startMission('t','m');await gateway.restartMission('t','m');const a=start.mock.calls[0][1].args[0],b=start.mock.calls[1][1].args[0];expect(a.scopeVersion).toBe(2);expect(a.missionExecutionId).not.toBe(b.missionExecutionId);});
 it('recover calls Reset once and retains the original execution identity',async()=>{const reset=vi.fn(async()=>({runId:'reset-run'}));const start=vi.fn();const signal=vi.fn();const gateway=Reflect.construct(TemporalGateway,[{workflowService:{resetWorkflowExecution:reset}},{options:{namespace:'default'},workflow:{start,getHandle:()=>({signal,fetchHistory:async()=>({events:[{workflowExecutionStartedEventAttributes:{input:{payloads:[{data:Buffer.from(JSON.stringify({...input,scopeVersion:2,missionExecutionId:'stable-e'}))}]}}},{eventId:16,workflowTaskCompletedEventAttributes:{}}]})})}},'queue']);const r=await gateway.recoverMission('t','m',{sourceRunId:'old',workflowTaskFinishEventId:16,requestId:'one-reset',pauseAfterReset:true});expect(r.missionExecutionId).toBe('stable-e');expect(reset).toHaveBeenCalledOnce();expect(start).not.toHaveBeenCalled();expect(signal).toHaveBeenCalledOnce();});
});
