import { hash } from 'argon2';
import { eq } from 'drizzle-orm';
import { createDatabaseClient } from './client.js';
import {
  actionCards,
  actionQueueReadModel,
  artifacts,
  artifactVersions,
  claimEvidenceLinks,
  claims,
  competitorProfiles,
  contactPointEvidenceLinks,
  contactPathReadModel,
  contactPoints,
  contactVerifications,
  entities,
  entityRelationships,
  evidenceItems,
  interactions,
  interactionClaimLinks,
  interactionEvidenceLinks,
  industryOpinions,
  marketRoutes,
  missionDashboardReadModel,
  missionEntities,
  missionProgressReadModel,
  missions,
  opportunities,
  opportunityBoardReadModel,
  opportunityContacts,
  opportunityScores,
  opportunityStakeholders,
  runReadModel,
  refreshProposals,
  sources,
  sourceSnapshots,
  stakeholderRoles,
  targetListReadModel,
  tenantMembers,
  tenants,
  timelineReadModel,
  users,
} from './schema/index.js';

const id = {
  tenant: '10000000-0000-4000-8000-000000000001', user: '10000000-0000-4000-8000-000000000002', mission: '10000000-0000-4000-8000-000000000003',
  source: '10000000-0000-4000-8000-000000000010', snapshot: '10000000-0000-4000-8000-000000000011', evidence: '10000000-0000-4000-8000-000000000012', claim: '10000000-0000-4000-8000-000000000013',
  routeArtifact: '10000000-0000-4000-8000-000000000020', routeVersion: '10000000-0000-4000-8000-000000000021', route: '10000000-0000-4000-8000-000000000022',
  refreshArtifact: '10000000-0000-4000-8000-000000000023', refreshVersion: '10000000-0000-4000-8000-000000000024',
  distributor: '10000000-0000-4000-8000-000000000030', epc: '10000000-0000-4000-8000-000000000031', endUser: '10000000-0000-4000-8000-000000000032', association: '10000000-0000-4000-8000-000000000033', exhibition: '10000000-0000-4000-8000-000000000034', competitor: '10000000-0000-4000-8000-000000000035', person: '10000000-0000-4000-8000-000000000036',
  relationship1: '10000000-0000-4000-8000-000000000037', relationship2: '10000000-0000-4000-8000-000000000038', relationship3: '10000000-0000-4000-8000-000000000039',
  stakeholder: '10000000-0000-4000-8000-000000000040', contact: '10000000-0000-4000-8000-000000000041', backupContact: '10000000-0000-4000-8000-000000000042', verification: '10000000-0000-4000-8000-000000000043',
  opportunity: '10000000-0000-4000-8000-000000000050', score: '10000000-0000-4000-8000-000000000051', card: '10000000-0000-4000-8000-000000000052', interaction: '10000000-0000-4000-8000-000000000053',
  interactionSource: '10000000-0000-4000-8000-000000000054', interactionSnapshot: '10000000-0000-4000-8000-000000000055', interactionEvidence: '10000000-0000-4000-8000-000000000056', interactionClaim: '10000000-0000-4000-8000-000000000057', interactionCard: '10000000-0000-4000-8000-000000000058',
  timeline1: '10000000-0000-4000-8000-000000000061', timeline2: '10000000-0000-4000-8000-000000000062', timeline3: '10000000-0000-4000-8000-000000000063', run1: '10000000-0000-4000-8000-000000000071', run2: '10000000-0000-4000-8000-000000000072',
} as const;

const demoUuid = (namespace: number, index: number): string => `${namespace.toString(16).padStart(8, '0')}-0000-4000-8000-${index.toString().padStart(12, '0')}`;

async function seed(): Promise<void> {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) throw new Error('DATABASE_URL is required');
  const client = createDatabaseClient(databaseUrl, 1);
  const now = new Date();
  const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1_000);
  const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1_000);
  try {
    const passwordHash = await hash(process.env.DEMO_PASSWORD ?? 'Demo123!');
    await client.db.insert(tenants).values({ id: id.tenant, name: 'Demo Industrial Workspace', slug: 'demo-industrial' }).onConflictDoNothing();
    await client.db.insert(users).values({ id: id.user, email: 'owner@demo.local', displayName: 'Demo Owner', passwordHash }).onConflictDoNothing();
    await client.db.insert(tenantMembers).values({ tenantId: id.tenant, userId: id.user, role: 'owner', status: 'active' }).onConflictDoNothing();
    await client.db.insert(missions).values({ id: id.mission, tenantId: id.tenant, name: 'Industrial Valve Germany Entry', companyName: 'Demo Flow Control Co., Ltd.', companyWebsite: 'https://demo-flow.example', productScope: 'Industrial ball, gate and butterfly valves for chemical processing and water infrastructure.', targetCountries: ['DE'], targetIndustries: ['Chemical Processing', 'Water Infrastructure'], targetProfiles: [{ type: 'distributor', description: 'German process-valve distributor with technical sales capability' }, { type: 'epc', description: 'EPC contractor involved in chemical and municipal projects' }], objective: 'Identify evidence-backed routes, reachable target organizations and executable first-contact actions.', successDefinition: 'Approve one market route, verify a primary contact path and execute one approved action card.', outputLanguages: ['en', 'de'], budgetConfig: { searches: 120, browserFetches: 240, modelTokens: 2_000_000, maxCostUsd: 75 }, status: 'running', currentStage: 'active', workflowId: 'mission-demo-active', createdBy: id.user }).onConflictDoNothing();

    await client.db.insert(sources).values({ id: id.source, tenantId: id.tenant, missionId: id.mission, sourceType: 'company_website', url: 'https://demo-flow.example/products', normalizedUrl: 'https://demo-flow.example/products', title: 'Demo Flow Control Product Catalog', publisher: 'Demo Flow Control Co., Ltd.', language: 'en', countryCode: 'CN', metadata: { fixture: true }, status: 'active' }).onConflictDoNothing();
    await client.db.insert(sourceSnapshots).values({ id: id.snapshot, sourceId: id.source, httpStatus: 200, contentHash: 'demo-product-catalog-sha256', objectKey: 'demo/mission/product-catalog.html', extractedText: 'The fictional demo manufacturer offers industrial ball, gate and butterfly valves with EN 10204 material traceability and API 598 pressure testing.', extractionMetadata: { fixture: true } }).onConflictDoNothing();
    await client.db.update(sources).set({ latestSnapshotId: id.snapshot }).where(eq(sources.id, id.source));

    await client.db.insert(artifacts).values([{ id: id.routeArtifact, tenantId: id.tenant, missionId: id.mission, artifactType: 'market_route_set', title: 'Germany market routes' }, { id: id.refreshArtifact, tenantId: id.tenant, missionId: id.mission, artifactType: 'refresh_proposal', title: 'Weekly evidence and opportunity update' }]).onConflictDoNothing();
    await client.db.insert(artifactVersions).values([{ id: id.routeVersion, artifactId: id.routeArtifact, versionNo: 1, status: 'accepted', payload: { routes: ['Technical distributor route'] }, summary: 'Technical distributor route approved for the demonstration.', acceptedByUserId: id.user, acceptedAt: yesterday }, { id: id.refreshVersion, artifactId: id.refreshArtifact, versionNo: 1, status: 'proposed', payload: { changeType: 'contact_change', contactPointId: id.contact, proposedConfidence: 95, reason: 'A second official supplier page repeats the procurement mailbox.' }, summary: 'Primary procurement email gained a second official-source confirmation.' }]).onConflictDoNothing();
    await client.db.update(artifacts).set({ currentVersionId: id.routeVersion }).where(eq(artifacts.id, id.routeArtifact));
    await client.db.insert(marketRoutes).values({ id: id.route, tenantId: id.tenant, missionId: id.mission, routeType: 'channel', title: 'Technical distributor route', hypothesis: 'A technically capable German distributor can shorten time to qualified industrial buyers while containing local service cost.', applicableScenarios: ['Chemical plant maintenance', 'Municipal water upgrades'], keyEntityTypes: ['organization', 'association', 'exhibition'], keyStakeholderRoles: ['distributor', 'technical_influencer', 'procurement'], primaryChannels: ['role_email', 'supplier_registration', 'exhibition_booking'], capabilityRequirements: ['EN documentation', 'Pressure test traceability', 'German or English technical support'], evidenceSummary: 'Demo capability catalog and public distributor fixture support the route.', counterEvidenceSummary: 'No verified installed base or local stock commitment is available.', confidence: 78, entryDifficulty: 58, timeToFirstContactDays: 14, resourceIntensity: 44, rank: 1, status: 'approved', artifactVersionId: id.routeVersion, decidedByUserId: id.user, decidedAt: yesterday }).onConflictDoNothing();

    await client.db.insert(claims).values({ id: id.claim, tenantId: id.tenant, missionId: id.mission, claimType: 'certification_and_testing', statement: 'Product documentation states EN 10204 material traceability and API 598 pressure testing.', valueJson: { standards: ['EN 10204', 'API 598'] }, status: 'observed', confidence: 88, origin: 'agent', impactLevel: 'high', artifactVersionId: id.routeVersion }).onConflictDoNothing();
    await client.db.insert(evidenceItems).values({ id: id.evidence, tenantId: id.tenant, missionId: id.mission, sourceSnapshotId: id.snapshot, excerpt: 'EN 10204 material traceability and API 598 pressure testing', locator: { selector: '#quality', line: 18 }, stance: 'support', relevance: 95, freshness: 85 }).onConflictDoNothing();
    await client.db.insert(claimEvidenceLinks).values({ claimId: id.claim, evidenceItemId: id.evidence, weight: 100 }).onConflictDoNothing();

    const entityRows = [
      { id: id.distributor, canonicalName: 'RheinWerk Distribution GmbH', entityType: 'organization' as const, website: 'https://rheinwerk.example', description: 'Fictional industrial distributor fixture.', roles: ['distributor', 'local_service_partner'], relevance: 90, target: 'high_priority' as const },
      { id: id.epc, canonicalName: 'EuroChem Projects GmbH', entityType: 'organization' as const, website: 'https://eurochem-projects.example', description: 'Fictional chemical EPC fixture.', roles: ['epc'], relevance: 82, target: 'target' as const },
      { id: id.endUser, canonicalName: 'NordWater Systems GmbH', entityType: 'organization' as const, website: 'https://nordwater.example', description: 'Fictional municipal water operator fixture.', roles: ['end_user'], relevance: 76, target: 'target' as const },
      { id: id.association, canonicalName: 'IndustrieArmaturen Verband', entityType: 'association' as const, website: 'https://iav.example', description: 'Fictional industry association fixture.', roles: ['association'], relevance: 64, target: 'observed' as const },
      { id: id.exhibition, canonicalName: 'ProcessTech Expo', entityType: 'exhibition' as const, website: 'https://processtech.example', description: 'Fictional process-industry exhibition fixture.', roles: ['exhibition'], relevance: 68, target: 'observed' as const },
      { id: id.competitor, canonicalName: 'VectorValve Europe GmbH', entityType: 'organization' as const, website: 'https://vectorvalve.example', description: 'Fictional competitor fixture.', roles: ['competitor'], relevance: 57, target: 'observed' as const },
    ];
    await client.db.insert(entities).values([...entityRows.map((row) => ({ id: row.id, tenantId: id.tenant, canonicalName: row.canonicalName, entityType: row.entityType, website: row.website, countryCode: 'DE', description: row.description, externalIds: { fixture: row.id }, status: 'active' as const })), { id: id.person, tenantId: id.tenant, canonicalName: 'Anna Becker', entityType: 'person', countryCode: 'DE', description: 'Fictional procurement contact fixture.', externalIds: { fixture: id.person }, status: 'active' }]).onConflictDoNothing();
    await client.db.insert(missionEntities).values(entityRows.map((row) => ({ missionId: id.mission, entityId: row.id, marketRoles: row.roles, relevanceScore: row.relevance, discoveryReason: 'Deterministic public-research fixture for local demonstration.', targetStatus: row.target, primaryRouteId: id.route }))).onConflictDoNothing();
    await client.db.insert(entityRelationships).values([{ id: id.relationship1, tenantId: id.tenant, missionId: id.mission, sourceEntityId: id.distributor, targetEntityId: id.endUser, relationshipType: 'supplies_to', directionality: 'directed', confidence: 72, attributes: { fixture: true }, status: 'proposed' }, { id: id.relationship2, tenantId: id.tenant, missionId: id.mission, sourceEntityId: id.epc, targetEntityId: id.endUser, relationshipType: 'designs_for', directionality: 'directed', confidence: 68, attributes: { fixture: true }, status: 'proposed' }, { id: id.relationship3, tenantId: id.tenant, missionId: id.mission, sourceEntityId: id.distributor, targetEntityId: id.association, relationshipType: 'member_of', directionality: 'directed', confidence: 80, attributes: { fixture: true }, status: 'confirmed' }]).onConflictDoNothing();

    await client.db.insert(stakeholderRoles).values({ id: id.stakeholder, tenantId: id.tenant, missionId: id.mission, organizationId: id.distributor, personId: id.person, roleType: 'procurement', title: 'Strategic Sourcing Manager', decisionInfluence: 82, contactPriority: 95, relevanceReason: 'Owns new supplier intake and initial commercial qualification.', confidence: 86, claimId: id.claim, status: 'confirmed' }).onConflictDoNothing();
    await client.db.insert(contactPoints).values([{ id: id.contact, tenantId: id.tenant, missionId: id.mission, organizationId: id.distributor, personId: id.person, stakeholderRoleId: id.stakeholder, contactType: 'role_email', value: 'procurement@rheinwerk.example', normalizedValue: 'procurement@rheinwerk.example', label: 'Procurement mailbox', isPublic: true, sourceId: id.source, sourceLocator: { fixture: true }, verificationStatus: 'cross_confirmed', confidence: 90, lastVerifiedAt: now, preferredRank: 1, language: 'de', timezone: 'Europe/Berlin', metadata: { fixture: true } }, { id: id.backupContact, tenantId: id.tenant, missionId: id.mission, organizationId: id.distributor, stakeholderRoleId: id.stakeholder, contactType: 'supplier_registration', value: 'https://rheinwerk.example/suppliers/register', normalizedValue: 'https://rheinwerk.example/suppliers/register', label: 'Supplier registration', isPublic: true, sourceId: id.source, sourceLocator: { fixture: true }, verificationStatus: 'source_confirmed', confidence: 78, lastVerifiedAt: yesterday, preferredRank: 2, language: 'de', timezone: 'Europe/Berlin', metadata: { fixture: true } }]).onConflictDoNothing();
    await client.db.insert(contactVerifications).values({ id: id.verification, tenantId: id.tenant, missionId: id.mission, contactPointId: id.contact, method: 'source_cross_check', result: 'passed', score: 90, details: { sources: 2, fixture: true }, verificationStatusBefore: 'source_confirmed', verificationStatusAfter: 'cross_confirmed', facts: { formatCheckPassed: true, exactValueListedByOfficialOrganization: true, exactValueLocatorEvidenceId: id.evidence, independentConfirmationGroups: ['rheinwerk.example', 'supplier.rheinwerk.example'], employmentConfirmationEvidenceIds: [id.evidence] } }).onConflictDoNothing();

    await client.db.insert(opportunities).values({ id: id.opportunity, tenantId: id.tenant, missionId: id.mission, organizationId: id.distributor, routeId: id.route, title: 'RheinWerk distributor onboarding', hypothesis: 'RheinWerk can qualify the product portfolio for German chemical maintenance buyers through its technical sales network.', status: 'approved', priority: 'high', score: 82, evidenceConfidence: 'high', commercialValueBand: 'high', estimatedSalesHours: '12', estimatedTechnicalHours: '8', estimatedMarketCostPoints: '4', resourceEfficiency: '3.42', nextAction: 'Send the approved procurement introduction and request a 20-minute qualification call.', ownerId: id.user, workflowId: 'opportunity-demo-approved' }).onConflictDoNothing();
    await client.db.insert(opportunityScores).values({ id: id.score, opportunityId: id.opportunity, versionNo: 1, productFit: 88, routeFit: 86, demandSignal: 72, timingSignal: 68, stakeholderRelevance: 90, contactability: 92, evidenceQuality: 78, strategicValue: 84, baseScore: '82.35', finalScore: 82, rationale: { productFit: 'Portfolio matches distributor focus.', contactability: 'Primary and backup public paths are verified.' }, generatedBy: 'mock_agent' }).onConflictDoNothing();
    await client.db.insert(opportunityStakeholders).values({ opportunityId: id.opportunity, stakeholderRoleId: id.stakeholder, roleInOpportunity: 'primary_decision_contact', rank: 1 }).onConflictDoNothing();
    await client.db.insert(opportunityContacts).values([{ opportunityId: id.opportunity, contactPointId: id.contact, usageType: 'primary', rank: 1 }, { opportunityId: id.opportunity, contactPointId: id.backupContact, usageType: 'backup', rank: 2 }]).onConflictDoNothing();
    await client.db.insert(actionCards).values({ id: id.card, tenantId: id.tenant, opportunityId: id.opportunity, versionNo: 1, status: 'approved', targetStakeholderRoleId: id.stakeholder, primaryContactPointId: id.contact, backupContactPointId: id.backupContact, channel: 'role_email', objective: 'Confirm portfolio fit and secure a 20-minute supplier qualification call.', contactReason: 'The target publicly accepts new industrial suppliers and serves chemical maintenance buyers aligned with the approved route.', timingReason: 'The current supplier-registration window is open and the verified procurement path is fresh.', stakeholderInterest: 'Reduce sourcing risk through documented material traceability, test records and responsive technical support.', valueHypothesis: 'A focused valve portfolio with traceable documents can expand available alternatives without adding qualification overhead.', emailSubject: 'Qualified industrial valve portfolio for RheinWerk supplier review', emailBody: 'Hello Ms. Becker,\n\nWe are contacting RheinWerk because your public supplier program and chemical-maintenance focus match our documented industrial valve portfolio. We can provide EN 10204 traceability and API 598 pressure-test records for qualification review.\n\nWould a 20-minute call next week be useful to confirm product fit and your onboarding requirements?\n\nRegards,\nDemo Flow Control', socialMessage: 'Hello Ms. Becker — we support industrial valve qualification with traceable material and pressure-test documentation. May I send a concise supplier pack for RheinWerk review?', callOpening: 'I am calling because RheinWerk publicly invites qualified industrial suppliers, and our documented valve range appears relevant to your chemical maintenance customers.', attachmentsRequired: ['Capability one-pager', 'Certification index'], followUpPlan: [{ day: 3, action: 'Follow up by email' }, { day: 8, action: 'Use supplier registration backup path' }], successSignals: ['Qualification call accepted', 'Supplier requirements received'], completionSignals: ['Email sent', 'Interaction result recorded'], ownerId: id.user, dueAt: tomorrow, approvedBy: id.user, approvedAt: yesterday }).onConflictDoNothing();
    await client.db.insert(interactions).values({ id: id.interaction, tenantId: id.tenant, missionId: id.mission, opportunityId: id.opportunity, actionCardId: id.card, interactionType: 'qualification_update', occurredAt: yesterday, actorUserId: id.user, targetContactPointId: id.contact, channel: 'internal', summary: 'Demo owner reviewed and approved the first-contact pack.', outcome: 'approved_for_contact', newFacts: [{ type: 'approval', value: true }], nextAction: 'Send approved email', followUpAt: tomorrow }).onConflictDoNothing();

    const additionalRouteIds = [demoUuid(21, 1), demoUuid(21, 2)];
    await client.db.insert(marketRoutes).values([
      { id: additionalRouteIds[0]!, tenantId: id.tenant, missionId: id.mission, routeType: 'epc', title: 'Chemical EPC onboarding route', hypothesis: 'Approved EPC vendor onboarding creates project access.', applicableScenarios: ['Chemical projects'], keyEntityTypes: ['organization'], keyStakeholderRoles: ['epc_engineer', 'procurement'], primaryChannels: ['supplier_registration', 'role_email'], capabilityRequirements: ['Project documentation'], evidenceSummary: 'Deterministic fixture evidence.', counterEvidenceSummary: 'No awarded contract claim.', confidence: 76, entryDifficulty: 68, timeToFirstContactDays: 35, resourceIntensity: 60, rank: 2, status: 'approved', artifactVersionId: id.routeVersion, decidedByUserId: id.user, decidedAt: yesterday },
      { id: additionalRouteIds[1]!, tenantId: id.tenant, missionId: id.mission, routeType: 'direct_purchase', title: 'Industrial end-user supplier route', hypothesis: 'Public supplier registration provides a direct path.', applicableScenarios: ['Maintenance sourcing'], keyEntityTypes: ['organization'], keyStakeholderRoles: ['supplier_onboarding', 'procurement'], primaryChannels: ['supplier_registration'], capabilityRequirements: ['Compliance pack'], evidenceSummary: 'Deterministic fixture evidence.', counterEvidenceSummary: 'Demand volume remains unknown.', confidence: 73, entryDifficulty: 72, timeToFirstContactDays: 42, resourceIntensity: 64, rank: 3, status: 'approved', artifactVersionId: id.routeVersion, decidedByUserId: id.user, decidedAt: yesterday },
    ]).onConflictDoNothing();

    const additionalTargetIds = Array.from({ length: 17 }, (_, index) => demoUuid(22, index + 1));
    await client.db.insert(entities).values(additionalTargetIds.map((entityId, index) => ({ id: entityId, tenantId: id.tenant, canonicalName: `Deterministic Target ${String(index + 4).padStart(2, '0')} GmbH`, entityType: 'organization' as const, website: `https://deterministic-target-${index + 4}.example`, countryCode: 'DE', description: 'Reserved-domain deterministic workflow fixture.', externalIds: { fixture: `target-${index + 4}` }, status: 'active' as const }))).onConflictDoNothing();
    await client.db.insert(missionEntities).values(additionalTargetIds.map((entityId, index) => ({ missionId: id.mission, entityId, marketRoles: [index % 2 === 0 ? 'distributor' : 'end_user'], relevanceScore: 75 - (index % 12), discoveryReason: 'Deterministic Mock Agent ecosystem result.', targetStatus: index < 7 ? 'high_priority' as const : 'target' as const, primaryRouteId: index % 3 === 0 ? id.route : additionalRouteIds[index % 2]! }))).onConflictDoNothing();

    const opportunityOrganizationIds = [id.epc, id.endUser, ...additionalTargetIds.slice(0, 7)];
    const generatedOpportunityRows = opportunityOrganizationIds.map((organizationId, index) => ({
      opportunityId: demoUuid(23, index + 1), scoreId: demoUuid(24, index + 1), stakeholderId: demoUuid(25, index + 1), primaryContactId: demoUuid(26, index * 2 + 1), backupContactId: demoUuid(26, index * 2 + 2), organizationId,
    }));
    for (const [index, row] of generatedOpportunityRows.entries()) {
      await client.db.insert(stakeholderRoles).values({ id: row.stakeholderId, tenantId: id.tenant, missionId: id.mission, organizationId: row.organizationId, roleType: 'procurement', title: 'Supplier Qualification', decisionInfluence: 80, contactPriority: 1, relevanceReason: 'Owns deterministic supplier qualification.', confidence: 85, status: 'confirmed' }).onConflictDoNothing();
      await client.db.insert(contactPoints).values([
        { id: row.primaryContactId, tenantId: id.tenant, missionId: id.mission, organizationId: row.organizationId, stakeholderRoleId: row.stakeholderId, contactType: 'role_email', value: `procurement-${index + 2}@target-${index + 2}.example`, normalizedValue: `procurement-${index + 2}@target-${index + 2}.example`, label: 'Primary procurement path', isPublic: true, sourceId: id.source, sourceLocator: { selector: '#procurement', fixture: true }, verificationStatus: 'cross_confirmed', confidence: 88, lastVerifiedAt: now, preferredRank: 1, language: 'de', timezone: 'Europe/Berlin', metadata: { fixture: true } },
        { id: row.backupContactId, tenantId: id.tenant, missionId: id.mission, organizationId: row.organizationId, stakeholderRoleId: row.stakeholderId, contactType: 'supplier_registration', value: `https://target-${index + 2}.example/suppliers`, normalizedValue: `https://target-${index + 2}.example/suppliers`, label: 'Backup supplier portal', isPublic: true, sourceId: id.source, sourceLocator: { selector: '#supplier-portal', fixture: true }, verificationStatus: 'source_confirmed', confidence: 80, lastVerifiedAt: now, preferredRank: 2, language: 'de', timezone: 'Europe/Berlin', metadata: { fixture: true } },
      ]).onConflictDoNothing();
      await client.db.insert(contactPointEvidenceLinks).values([{ tenantId: id.tenant, missionId: id.mission, contactPointId: row.primaryContactId, evidenceItemId: id.evidence, relationType: 'direct_listing', sourceAuthority: 'official_organization', independentGroupKey: `target-${index + 2}.example`, supportsValue: true, observedAt: now }, { tenantId: id.tenant, missionId: id.mission, contactPointId: row.backupContactId, evidenceItemId: id.evidence, relationType: 'direct_listing', sourceAuthority: 'official_organization', independentGroupKey: `target-${index + 2}.example`, supportsValue: true, observedAt: now }]).onConflictDoNothing();
      await client.db.insert(contactVerifications).values({ id: demoUuid(27, index + 1), tenantId: id.tenant, missionId: id.mission, contactPointId: row.primaryContactId, method: 'source_cross_check', result: 'passed', score: 88, details: { fixture: true }, verificationStatusBefore: 'source_confirmed', verificationStatusAfter: 'cross_confirmed', facts: { formatCheckPassed: true, exactValueListedByOfficialOrganization: true, exactValueLocatorEvidenceId: id.evidence, independentConfirmationGroups: [`target-${index + 2}.example`], employmentConfirmationEvidenceIds: [] } }).onConflictDoNothing();
      await client.db.insert(opportunities).values({ id: row.opportunityId, tenantId: id.tenant, missionId: id.mission, organizationId: row.organizationId, routeId: index % 3 === 0 ? id.route : additionalRouteIds[index % 2]!, title: `Deterministic qualification opportunity ${index + 2}`, hypothesis: 'Mock evidence and public contact paths satisfy the deterministic demo gate.', status: index < 4 ? 'action_ready' : 'contact_path_verified', priority: index < 5 ? 'high' : 'medium', score: 80 - index, evidenceConfidence: 'high', commercialValueBand: 'high', estimatedSalesHours: '8', estimatedTechnicalHours: '4', estimatedMarketCostPoints: '3', resourceEfficiency: '4.2', nextAction: index < 4 ? 'Review generated Action Card' : 'Generate first-contact Action Card', workflowId: `opportunity:${id.tenant}:${row.opportunityId}` }).onConflictDoNothing();
      await client.db.insert(opportunityScores).values({ id: row.scoreId, opportunityId: row.opportunityId, versionNo: 1, productFit: 85, routeFit: 82, demandSignal: 70, timingSignal: 65, stakeholderRelevance: 84, contactability: 90, evidenceQuality: 82, strategicValue: 76, baseScore: String(80 - index), finalScore: 80 - index, rationale: { fixture: 'Deterministic workflow score.' }, generatedBy: 'mock_agent' }).onConflictDoNothing();
      await client.db.insert(opportunityStakeholders).values({ opportunityId: row.opportunityId, stakeholderRoleId: row.stakeholderId, roleInOpportunity: 'primary_decision_contact', rank: 1 }).onConflictDoNothing();
      await client.db.insert(opportunityContacts).values([{ opportunityId: row.opportunityId, contactPointId: row.primaryContactId, usageType: 'primary', rank: 1 }, { opportunityId: row.opportunityId, contactPointId: row.backupContactId, usageType: 'backup', rank: 2 }]).onConflictDoNothing();
      if (index < 4) await client.db.insert(actionCards).values({ id: demoUuid(28, index + 1), tenantId: id.tenant, opportunityId: row.opportunityId, versionNo: 1, status: 'review', targetStakeholderRoleId: row.stakeholderId, primaryContactPointId: row.primaryContactId, backupContactPointId: row.backupContactId, channel: 'role_email', objective: 'Confirm supplier qualification requirements.', contactReason: 'The organization matches an approved route and publishes a supplier path.', timingReason: 'The public evidence snapshot is current.', stakeholderInterest: 'Reduce sourcing risk with traceable product documentation.', valueHypothesis: 'A focused documented portfolio can simplify qualification.', emailSubject: 'Industrial supplier qualification inquiry', emailBody: 'This deterministic fixture contains a complete first-contact message.', socialMessage: 'Please direct this qualification inquiry to procurement.', callOpening: 'Calling to confirm the supplier qualification route.', attachmentsRequired: ['Capability one-pager'], followUpPlan: [{ offsetDays: 3, objective: 'Confirm receipt' }], successSignals: ['Qualification requirements shared'], completionSignals: ['Response recorded'], dueAt: tomorrow }).onConflictDoNothing();
    }
    await client.db.insert(contactPointEvidenceLinks).values([{ tenantId: id.tenant, missionId: id.mission, contactPointId: id.contact, evidenceItemId: id.evidence, relationType: 'direct_listing', sourceAuthority: 'official_organization', independentGroupKey: 'rheinwerk.example', supportsValue: true, supportsEmployment: true, observedAt: now }, { tenantId: id.tenant, missionId: id.mission, contactPointId: id.backupContact, evidenceItemId: id.evidence, relationType: 'direct_listing', sourceAuthority: 'official_organization', independentGroupKey: 'rheinwerk.example', supportsValue: true, observedAt: now }]).onConflictDoNothing();
    await client.db.update(interactions).set({ rawContent: 'The target requested supplier registration documents before commercial review.', rawContentHash: 'deterministic-interaction-content-sha256', interpretationStatus: 'completed', interpretedAt: now, newFacts: [{ type: 'supplier_requirement', value: 'Complete supplier registration' }] }).where(eq(interactions.id, id.interaction));
    await client.db.insert(sources).values({ id: id.interactionSource, tenantId: id.tenant, missionId: id.mission, sourceType: 'interaction_record', title: 'RheinWerk response interaction', publisher: 'Demo Owner', language: 'en', metadata: { fixture: true, interactionId: id.interaction, authority: 'user_supplied' }, status: 'active' }).onConflictDoNothing();
    await client.db.insert(sourceSnapshots).values({ id: id.interactionSnapshot, sourceId: id.interactionSource, contentHash: 'deterministic-interaction-content-sha256', objectKey: `demo/interactions/${id.interaction}.txt`, extractedText: 'The target requested supplier registration documents before commercial review.', extractionMetadata: { fixture: true, interactionId: id.interaction } }).onConflictDoNothing();
    await client.db.update(sources).set({ latestSnapshotId: id.interactionSnapshot }).where(eq(sources.id, id.interactionSource));
    await client.db.insert(evidenceItems).values({ id: id.interactionEvidence, tenantId: id.tenant, missionId: id.mission, sourceSnapshotId: id.interactionSnapshot, excerpt: 'The target requested supplier registration documents before commercial review.', locator: { interactionId: id.interaction, field: 'rawContent' }, stance: 'support', relevance: 100, freshness: 100 }).onConflictDoNothing();
    await client.db.insert(claims).values({ id: id.interactionClaim, tenantId: id.tenant, missionId: id.mission, subjectEntityId: id.distributor, claimType: 'supplier_requirement', statement: 'RheinWerk requires supplier registration documents before commercial review.', valueJson: { requirement: 'Complete supplier registration' }, status: 'observed', confidence: 95, origin: 'user', impactLevel: 'high' }).onConflictDoNothing();
    await client.db.insert(claimEvidenceLinks).values({ claimId: id.interactionClaim, evidenceItemId: id.interactionEvidence, weight: 100 }).onConflictDoNothing();
    await client.db.insert(interactionClaimLinks).values({ interactionId: id.interaction, claimId: id.interactionClaim, changeType: 'created' }).onConflictDoNothing();
    await client.db.insert(interactionEvidenceLinks).values({ interactionId: id.interaction, evidenceItemId: id.interactionEvidence }).onConflictDoNothing();
    const [approvedCard] = await client.db.select().from(actionCards).where(eq(actionCards.id, id.card)).limit(1);
    if (approvedCard) await client.db.insert(actionCards).values({ ...approvedCard, id: id.interactionCard, versionNo: 2, basedOnVersionNo: 1, feedbackRefs: [id.interaction], status: 'review', emailSubject: 'Supplier registration documents for RheinWerk review', emailBody: 'Hello Ms. Becker,\n\nThank you for clarifying the next step. Attached is the requested supplier registration documentation for commercial review. Please let us know whether any additional qualification records are required.\n\nRegards,\nDemo Flow Control', approvedBy: null, approvedAt: null, createdAt: now, updatedAt: now }).onConflictDoNothing();
    await client.db.update(opportunities).set({ status: 'responded', nextAction: 'Prepare supplier registration documents', updatedAt: now }).where(eq(opportunities.id, id.opportunity));
    await client.db.insert(refreshProposals).values([{ id: demoUuid(29, 1), tenantId: id.tenant, missionId: id.mission, artifactVersionId: id.refreshVersion, triggerType: 'manual', changedSourceCount: 1, reverifiedContactCount: 10, changedCompetitorCount: 1, affectedOpportunityIds: [id.opportunity] }, { id: demoUuid(29, 2), tenantId: id.tenant, missionId: id.mission, artifactVersionId: id.refreshVersion, triggerType: 'scheduled', changedSourceCount: 1, reverifiedContactCount: 10, changedCompetitorCount: 1, affectedOpportunityIds: generatedOpportunityRows.slice(0, 2).map((row) => row.opportunityId) }]).onConflictDoNothing();
    await client.db.insert(competitorProfiles).values(Array.from({ length: 3 }, (_, index) => ({ id: demoUuid(30, index + 1), tenantId: id.tenant, missionId: id.mission, entityId: id.competitor, marketPresenceSummary: `Deterministic competitor profile ${index + 1}`, routePatterns: ['channel'], localChannels: [], exhibitions: [], publicCustomers: [], certifications: ['ISO 9001'], serviceNetwork: ['DE'], marketMinimums: ['Documentation'], opportunityGaps: ['Public onboarding'], confidence: 80 - index, artifactVersionId: id.routeVersion }))).onConflictDoNothing();
    await client.db.insert(industryOpinions).values(Array.from({ length: 5 }, (_, index) => ({ id: demoUuid(31, index + 1), tenantId: id.tenant, missionId: id.mission, organizationEntityId: id.association, sourceId: id.source, topic: `Deterministic industry opinion ${index + 1}`, positionSummary: 'Traceability and qualification speed remain important.', marketImplication: 'Lead with current evidence.', credibilityScore: 75 + index, contactable: index % 2 === 0, artifactVersionId: id.routeVersion }))).onConflictDoNothing();

    await client.db.insert(missionDashboardReadModel).values({ missionId: id.mission, tenantId: id.tenant, missionName: 'Industrial Valve Germany Entry', companyName: 'Demo Flow Control Co., Ltd.', targetCountries: ['DE'], status: 'running', currentStage: 'active', approvedRouteCount: 3, targetCount: 20, verifiedContactCount: 20, actionCardCount: 5, pendingApprovalCount: 4, highPriorityOpportunityCount: 6, weeklyInteractionCount: 1, totalCostAmount: '0' }).onConflictDoUpdate({ target: missionDashboardReadModel.missionId, set: { approvedRouteCount: 3, targetCount: 20, verifiedContactCount: 20, actionCardCount: 5, highPriorityOpportunityCount: 6, updatedAt: now } });
    await client.db.insert(missionProgressReadModel).values({ tenantId: id.tenant, missionId: id.mission, stage: 'active', stageProgress: 90, completedSteps: ['Mission brief', 'Company evidence', 'Market routes', 'Ecosystem', 'Targets', 'Contact paths', 'Opportunity qualification'], runningSteps: ['Approved action execution'], pendingSteps: ['Interaction interpretation', 'Weekly refresh'], failedSteps: [], activeChildWorkflows: 1, childOpportunityTotal: 1, childOpportunityActionReady: 1, childOpportunityActive: 1, childOpportunityClosed: 0, readModelVersion: 3, lastEventId: id.timeline3, budgetUsage: { searches: 0.18, browserFetches: 0.12, modelTokens: 0.24, maxCostUsd: 0 }, pendingUserActions: ['Execute approved action card', 'Review weekly refresh proposal'] }).onConflictDoNothing();
    await client.db.insert(targetListReadModel).values(entityRows.filter((row) => row.target !== 'observed').map((row, index) => ({ missionId: id.mission, entityId: row.id, organizationName: row.canonicalName, website: row.website, countryCode: 'DE', marketRoles: row.roles, primaryRouteTitle: 'Technical distributor route', productFit: 88 - index * 8, demandSignal: 74 - index * 5, contactability: row.id === id.distributor ? 92 : 55, evidenceQuality: 78 - index * 4, finalScore: row.relevance, targetStatus: row.target, opportunityId: row.id === id.distributor ? id.opportunity : undefined }))).onConflictDoNothing();
    await client.db.insert(contactPathReadModel).values([{ missionId: id.mission, contactPointId: id.contact, organizationId: id.distributor, organizationName: 'RheinWerk Distribution GmbH', stakeholderRoleId: id.stakeholder, stakeholderRoleType: 'procurement', personName: 'Anna Becker', personTitle: 'Strategic Sourcing Manager', contactType: 'role_email', value: 'procurement@rheinwerk.example', sourceTitle: 'Demo Flow Control Product Catalog', sourceUrl: 'https://demo-flow.example/products', verificationStatus: 'cross_confirmed', verificationScore: 90, lastVerifiedAt: now, preferredRank: 1, usageStatus: 'primary' }, { missionId: id.mission, contactPointId: id.backupContact, organizationId: id.distributor, organizationName: 'RheinWerk Distribution GmbH', stakeholderRoleId: id.stakeholder, stakeholderRoleType: 'supplier_onboarding', contactType: 'supplier_registration', value: 'https://rheinwerk.example/suppliers/register', sourceTitle: 'Supplier registration fixture', sourceUrl: 'https://rheinwerk.example/suppliers/register', verificationStatus: 'source_confirmed', verificationScore: 78, lastVerifiedAt: yesterday, preferredRank: 2, usageStatus: 'backup' }]).onConflictDoNothing();
    await client.db.insert(opportunityBoardReadModel).values({ missionId: id.mission, opportunityId: id.opportunity, organizationName: 'RheinWerk Distribution GmbH', routeTitle: 'Technical distributor route', status: 'approved', priority: 'high', score: 82, commercialValueBand: 'high', resourceEfficiency: '3.42', primaryContactSummary: 'Anna Becker · procurement@rheinwerk.example', nextAction: 'Send approved procurement introduction', ownerName: 'Demo Owner' }).onConflictDoNothing();
    await client.db.insert(actionQueueReadModel).values({ missionId: id.mission, actionCardId: id.card, opportunityId: id.opportunity, organizationName: 'RheinWerk Distribution GmbH', stakeholderSummary: 'Anna Becker · Procurement', primaryContactSummary: 'procurement@rheinwerk.example', status: 'approved', channel: 'role_email', objective: 'Confirm portfolio fit and secure a 20-minute supplier qualification call.', ownerName: 'Demo Owner', dueAt: tomorrow }).onConflictDoNothing();
    await client.db.insert(timelineReadModel).values([{ eventId: id.timeline1, tenantId: id.tenant, missionId: id.mission, eventType: 'mission.started.v1', actorType: 'user', actorDisplayName: 'Demo Owner', aggregateType: 'mission', aggregateId: id.mission, correlationId: id.timeline1, aggregateVersion: 1, schemaVersion: 1, title: 'Market-entry mission started', summary: 'The deterministic Germany market-entry workflow started in Mock mode.', evidenceRefs: [], occurredAt: new Date(now.getTime() - 72 * 60 * 60 * 1_000) }, { eventId: id.timeline2, tenantId: id.tenant, missionId: id.mission, eventType: 'market_route.approved.v1', actorType: 'user', actorDisplayName: 'Demo Owner', aggregateType: 'market_route', aggregateId: id.route, correlationId: id.timeline2, aggregateVersion: 1, schemaVersion: 1, title: 'Technical distributor route approved', summary: 'The route passed the evidence, capability and contact-channel review.', evidenceRefs: [id.evidence], occurredAt: new Date(now.getTime() - 48 * 60 * 60 * 1_000) }, { eventId: id.timeline3, tenantId: id.tenant, missionId: id.mission, eventType: 'action_card.approved.v1', actorType: 'user', actorDisplayName: 'Demo Owner', aggregateType: 'action_card', aggregateId: id.card, correlationId: id.timeline3, aggregateVersion: 1, schemaVersion: 1, title: 'First-contact action approved', summary: 'Email content and backup supplier-registration path are ready for execution.', evidenceRefs: [id.evidence], occurredAt: yesterday }]).onConflictDoNothing();
    await client.db.insert(runReadModel).values([{ runId: id.run1, tenantId: id.tenant, missionId: id.mission, runType: 'agent', skillKey: 'market_route_researcher', status: 'succeeded', modelName: 'mock-deterministic-v1', contextVersion: 1, inputContextHash: 'demo-route-context-sha256', promptVersion: 1, evidenceItemIds: [id.evidence], toolRuns: [], inputTokens: 1450, outputTokens: 890, costAmount: '0', durationMs: 480, traceId: 'demo-route-trace', startedAt: new Date(now.getTime() - 49 * 60 * 60 * 1_000), completedAt: new Date(now.getTime() - 49 * 60 * 60 * 1_000 + 480) }, { runId: id.run2, tenantId: id.tenant, missionId: id.mission, runType: 'agent', skillKey: 'action_card_builder', status: 'succeeded', modelName: 'mock-deterministic-v1', contextVersion: 1, inputContextHash: 'demo-action-context-sha256', promptVersion: 1, evidenceItemIds: [id.evidence], toolRuns: [], inputTokens: 1180, outputTokens: 720, costAmount: '0', durationMs: 360, traceId: 'demo-action-trace', startedAt: new Date(now.getTime() - 25 * 60 * 60 * 1_000), completedAt: new Date(now.getTime() - 25 * 60 * 60 * 1_000 + 360) }]).onConflictDoNothing();
    process.stdout.write(`Demo seed ready: owner@demo.local / ${process.env.DEMO_PASSWORD ? '[DEMO_PASSWORD]' : 'Demo123!'}\nMission: ${id.mission}\n`);
  } finally {
    await client.close();
  }
}

await seed();
