import { downloadDisposition } from './download-filename.js';
import { Body, Controller, Get, Param, Patch, Post, Query, Res } from '@nestjs/common';
import type { FastifyReply } from 'fastify';
import { z } from 'zod';
import type { AuthContext } from '../common/auth-context.js';
import { CurrentAuth } from '../common/auth-context.js';
import { ZodPipe } from '../common/zod.pipe.js';
import { MarketService } from './market.service.js';

const contactUpdateSchema = z.object({ value: z.string().optional(), label: z.string().optional(), preferredRank: z.number().int().positive().optional(), language: z.string().optional(), timezone: z.string().optional(), verificationStatus: z.enum(['discovered','format_valid','source_confirmed','cross_confirmed','manually_confirmed','stale','invalid']).optional() });
const opportunityCreateSchema = z.object({ organizationId: z.uuid(), routeId: z.uuid(), title: z.string().optional(), hypothesis: z.string().optional(), priority: z.enum(['low','medium','high','critical']).optional() });
const opportunityUpdateSchema = z.object({ title: z.string().optional(), hypothesis: z.string().optional(), priority: z.enum(['low','medium','high','critical']).optional(), ownerId: z.uuid().nullable().optional(), nextAction: z.string().optional(), commercialValueBand: z.enum(['very_low','low','medium','high','strategic']).optional() });
const actionUpdateSchema = z.object({ expectedVersionNo: z.number().int().positive(), objective: z.string().optional(), contactReason: z.string().optional(), timingReason: z.string().optional(), stakeholderInterest: z.string().optional(), valueHypothesis: z.string().optional(), emailSubject: z.string().nullable().optional(), emailBody: z.string().nullable().optional(), socialMessage: z.string().nullable().optional(), callOpening: z.string().nullable().optional(), contactFormMessage: z.string().nullable().optional(), ownerId: z.uuid().nullable().optional(), dueAt: z.coerce.date().nullable().optional() });
const actionChangesSchema = z.object({ comment: z.string().optional() });
const actionDecisionSchema = z.object({ decision: z.enum(['approve', 'request_changes']), expectedVersionNo: z.number().int().positive(), comment: z.string().optional() }).superRefine((value, context) => { if (value.decision === 'request_changes' && !value.comment?.trim()) context.addIssue({ code: 'custom', path: ['comment'], message: 'comment is required for request_changes' }); });
const interactionSchema = z.object({ actionCardId: z.uuid().optional(), interactionType: z.enum(['email_sent','message_sent','call','meeting','form_submitted','supplier_registration','exhibition_meeting','referral','response','qualification_update','sample_sent','quotation_sent']), occurredAt: z.iso.datetime(), targetContactPointId: z.uuid().optional(), channel: z.string().optional(), summary: z.string().min(1), rawContent: z.string().min(1), outcome: z.string().min(1), submittedFacts: z.array(z.record(z.string(), z.unknown())).optional(), nextAction: z.string().optional(), followUpAt: z.iso.datetime().optional() });

@Controller('api/v1/missions/:missionId')
export class ExecutionController {
  constructor(private readonly service: MarketService) {}

  @Get('contact-points') contacts(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string) { return this.service.contacts(auth, missionId); }
  @Get('contact-points/:contactPointId') contact(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('contactPointId') contactPointId: string) { return this.service.contact(auth, missionId, contactPointId); }
  @Post('contact-points/:contactPointId/verify') verifyContact(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('contactPointId') contactPointId: string) { return this.service.verifyContact(auth, missionId, contactPointId); }
  @Post('contact-points/:contactPointId/confirm') confirmContact(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('contactPointId') contactPointId: string) { return this.service.confirmContact(auth, missionId, contactPointId); }
  @Post('contact-points/:contactPointId/mark-stale') staleContact(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('contactPointId') contactPointId: string) { return this.service.markContactStale(auth, missionId, contactPointId); }
  @Patch('contact-points/:contactPointId') updateContact(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('contactPointId') contactPointId: string, @Body(new ZodPipe(contactUpdateSchema)) body: z.infer<typeof contactUpdateSchema>) { return this.service.updateContact(auth, missionId, contactPointId, body); }
  @Post('entities/:entityId/contact-research') researchContacts(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('entityId') entityId: string) { return this.service.researchContacts(auth, missionId, entityId); }

  @Get('opportunities') opportunities(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string) { return this.service.opportunities(auth, missionId); }
  @Get('opportunities/:opportunityId') opportunity(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('opportunityId') opportunityId: string) { return this.service.opportunity(auth, missionId, opportunityId); }
  @Get('opportunities/:opportunityId/workflow-progress') opportunityProgress(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('opportunityId') opportunityId: string) { return this.service.opportunityWorkflowProgress(auth, missionId, opportunityId); }
  @Post('opportunities') createOpportunity(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Body(new ZodPipe(opportunityCreateSchema)) body: z.infer<typeof opportunityCreateSchema>) { return this.service.createOpportunity(auth, missionId, body.organizationId, body); }
  @Patch('opportunities/:opportunityId') updateOpportunity(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('opportunityId') opportunityId: string, @Body(new ZodPipe(opportunityUpdateSchema)) body: z.infer<typeof opportunityUpdateSchema>) { return this.service.updateOpportunity(auth, missionId, opportunityId, body); }
  @Post('opportunities/:opportunityId/research') researchOpportunity(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('opportunityId') opportunityId: string) { return this.service.researchOpportunity(auth, missionId, opportunityId); }
  @Post('opportunities/:opportunityId/pause') pauseOpportunity(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('opportunityId') opportunityId: string) { return this.service.pauseOpportunity(auth, missionId, opportunityId); }
  @Post('opportunities/:opportunityId/resume') resumeOpportunity(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('opportunityId') opportunityId: string) { return this.service.resumeOpportunity(auth, missionId, opportunityId); }
  @Post('opportunities/:opportunityId/archive') archiveOpportunity(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('opportunityId') opportunityId: string) { return this.service.archiveOpportunity(auth, missionId, opportunityId); }
  @Get('opportunities/:opportunityId/scores') scores(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('opportunityId') opportunityId: string) { return this.service.scores(auth, missionId, opportunityId); }

  @Get('action-cards') actionCards(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string) { return this.service.actionCards(auth, missionId); }
  @Get('action-cards/:actionCardId') actionCard(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('actionCardId') actionCardId: string) { return this.service.actionCard(auth, missionId, actionCardId); }
  @Patch('action-cards/:actionCardId') updateActionCard(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('actionCardId') actionCardId: string, @Body(new ZodPipe(actionUpdateSchema)) body: z.infer<typeof actionUpdateSchema>) { return this.service.updateActionCard(auth, missionId, actionCardId, body); }
  @Post('action-cards/:actionCardId/approve') approveActionCard(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('actionCardId') actionCardId: string) { return this.service.approveActionCard(auth, missionId, actionCardId); }
  @Post('action-cards/:actionCardId/request-changes') requestChanges(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('actionCardId') actionCardId: string, @Body(new ZodPipe(actionChangesSchema)) body: z.infer<typeof actionChangesSchema>) { return this.service.requestActionChanges(auth, missionId, actionCardId, body.comment); }
  @Post('action-cards/:actionCardId/decision') decision(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('actionCardId') actionCardId: string, @Body(new ZodPipe(actionDecisionSchema)) body: z.infer<typeof actionDecisionSchema>) { return this.service.decideActionCard(auth, missionId, actionCardId, body); }
  @Post('action-cards/:actionCardId/regenerate') regenerate(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('actionCardId') actionCardId: string) { return this.service.regenerateActionCard(auth, missionId, actionCardId); }
  @Post('action-cards/:actionCardId/execute') execute(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('actionCardId') actionCardId: string) { return this.service.executeActionCard(auth, missionId, actionCardId); }
  @Get('action-cards/:actionCardId/export') async export(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('actionCardId') actionCardId: string, @Query('format') format: string | undefined, @Res() reply: FastifyReply) { const result = await this.service.actionCardExport(auth, missionId, actionCardId, format === 'csv' ? 'csv' : 'markdown'); return reply.header('Content-Type', result.contentType).header('Content-Disposition', downloadDisposition(result.filename)).send(result.content); }

  @Post('opportunities/:opportunityId/interactions') addInteraction(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('opportunityId') opportunityId: string, @Body(new ZodPipe(interactionSchema)) body: z.infer<typeof interactionSchema>) { return this.service.addInteraction(auth, missionId, opportunityId, body); }
  @Get('opportunities/:opportunityId/interactions') opportunityInteractions(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string, @Param('opportunityId') opportunityId: string) { return this.service.interactions(auth, missionId, opportunityId); }
  @Get('interactions') interactions(@CurrentAuth() auth: AuthContext, @Param('missionId') missionId: string) { return this.service.interactions(auth, missionId); }
}
