import { Download } from 'lucide-react';
import { CommandButton } from '@/components/command-button';
import { DataTable } from '@/components/data-table';
import { EmptyState, ErrorState } from '@/components/states';
import { Panel } from '@/components/panel';
import { PageHeader } from '@/components/page-header';
import { Confidence, StatusBadge } from '@/components/status';
import { safeApi } from '@/lib/api';
import type { EntityRow } from '@/lib/types';

export default async function TargetsPage({ params }: { params: Promise<{ missionId: string }> }) { const { missionId } = await params; const result = await safeApi<EntityRow[]>(`/api/v1/missions/${missionId}/targets`); if (result.error) return <ErrorState message={result.error.message} />; const rows = result.data ?? []; return <><PageHeader title="目标组织" description="根据路线适配、产品适配、需求信号、可触达性、证据质量和预计销售工时筛选目标。" actions={<button className="button button-secondary"><Download />导出</button>} /><Panel title="目标排序" description={`${rows.length} 个目标组织`} noPadding><DataTable rows={rows} getRowKey={(row) => row.entity.id} columns={[{ key: 'rank', label: '排名', render: () => <strong>—</strong> }, { key: 'organization', label: '组织', render: (row) => <div><div className="cell-primary">{row.entity.canonicalName}</div><div className="cell-secondary">{row.entity.website ?? '官方网站未知'}</div></div> }, { key: 'market', label: '市场角色', render: (row) => row.mission?.marketRoles.join(', ') ?? 'Unknown' }, { key: 'location', label: '国家 / 城市', render: (row) => [row.entity.countryCode, row.entity.city].filter(Boolean).join(' · ') || '—' }, { key: 'score', label: '相关性', render: (row) => <Confidence value={row.mission?.relevanceScore ?? 0} /> }, { key: 'status', label: '状态', render: (row) => <StatusBadge value={row.mission?.targetStatus ?? 'observed'} /> }, { key: 'action', label: '操作', align: 'right', render: (row) => <div className="row-actions"><CommandButton path={`/api/v1/missions/${missionId}/targets/${row.entity.id}/create-opportunity`} body={{}} label="创建机会" className="button button-primary" /><CommandButton path={`/api/v1/missions/${missionId}/entities/${row.entity.id}/research`} label="补充研究" className="button button-ghost" /></div> }]} empty={<EmptyState title="目标组织尚未形成" description="生态实体完成消歧和排序后，符合 Target Gate 的组织会进入这里。" />} /></Panel><div style={{ height: 18 }} /><Panel title="Target Gate"><div className="form-grid"><div><strong>实体身份</strong><div className="cell-secondary">消歧完成，存在官网或官方注册信息。</div></div><div><strong>路线关系</strong><div className="cell-secondary">市场角色明确，并与已批准路线相关。</div></div><div><strong>产品适配</strong><div className="cell-secondary">product_fit ≥ 50。</div></div><div><strong>证据质量</strong><div className="cell-secondary">evidence_quality ≥ 40。</div></div></div></Panel></>; }
